<a href="https://colab.research.google.com/github/parksuejin1026/2026_BDA_Study/blob/main/Week5/05Week_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

# PANDAS

Series : 하나의 열

In [3]:
s = pd.Series([1, 3, 5, np.nan, 6, 8], name = 'first')
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [4]:
s.name # 열이름

'first'

In [5]:
s.index # 인덱스 유형

RangeIndex(start=0, stop=6, step=1)

In [6]:
s.values # 열 값들 배열로 출력

array([ 1.,  3.,  5., nan,  6.,  8.])

In [7]:
s.shape

(6,)

In [8]:
s.size

6

In [9]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
Name: first, dtype: float64

In [10]:
s[1]

np.float64(3.0)

In [11]:
s[1:5]

1    3.0
2    5.0
3    NaN
4    6.0
Name: first, dtype: float64

In [12]:
s.index = list('abcdef') # 리스트로 변환하여 6개의 인덱스 생성
s

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [13]:
print(s['b'], s['d'])

3.0 nan

In [14]:
s['c':'e']

c    5.0
d    NaN
e    6.0
Name: first, dtype: float64

In [15]:
s['b':'f']

b    3.0
c    5.0
d    NaN
e    6.0
f    8.0
Name: first, dtype: float64

In [16]:
s[0:3]

a    1.0
b    3.0
c    5.0
Name: first, dtype: float64

In [19]:
s1 = s[1:4]
s1

b    3.0
c    5.0
d    NaN
Name: first, dtype: float64

In [20]:
s1[0]

/tmp/ipykernel_8069/643609873.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  s1[0]

np.float64(3.0)

In [21]:
s1[0] = 10
s1

/tmp/ipykernel_8069/1715506060.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s1[0] = 10

b    10.0
c     5.0
d     NaN
Name: first, dtype: float64

In [23]:
s

a     1.0
b    10.0
c     5.0
d     NaN
e     6.0
f     8.0
Name: first, dtype: float64

In [24]:
s.index = np.arange(1, 7)
s

1     1.0
2    10.0
3     5.0
4     NaN
5     6.0
6     8.0
Name: first, dtype: float64

In [25]:
s[1]

np.float64(1.0)

In [26]:
s[0]

KeyError: 0

In [27]:
s[1:3]

2    10.0
3     5.0
Name: first, dtype: float64

In [29]:
age = pd.Series([9, 17, 32, 45, 65, 98], index = list('abcdef'), name = 'age')
age

a     9
b    17
c    32
d    45
e    65
f    98
Name: age, dtype: int64

In [30]:
age['b']

np.int64(17)

In [31]:
age[[1, 3, 5]]

/tmp/ipykernel_8069/1546391730.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age[[1, 3, 5]]

b    17
d    45
f    98
Name: age, dtype: int64

In [32]:
age[['a', 'f', 'd']]

a     9
f    98
d    45
Name: age, dtype: int64

In [33]:
age[['c']]

c    32
Name: age, dtype: int64

In [34]:
s = pd.Series([3, 6, -3, 0, -4, 8, -7])
s

0    3
1    6
2   -3
3    0
4   -4
5    8
6   -7
dtype: int64